package ex32;

public class Ex32 {

    public static void main(String[] args) {

        int a;
        a = 0;
        System.out.println(a);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);
        a = a + 1;
        System.out.println(a + 1);

    }

}
