
package ex33;

public class Ex33 {

    public static void main(String[] args) {
    
        int a;
        a = 150;
        System.out.println(a);
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
        a = a + 3;
        System.out.println(a + 3);
    }
    
}
